### PR TITLE
Discern between UTF8 and UTF8BOM when writing

### PR DESCRIPTION
**Pull request by WallSoGB**
Fixes Starfield not reading correctly the created INI file.

### CODE REVIEW

**Comment by Aemony** [comment]
To summarize the chat with Kal:

- Default behaviour needs to be with BOM as this is apparently required for all Unreal Engine configs SK allows changing.
- BOM behavior should be changeable through a parameter in `iSK_INI` -- for example something like this:
```cpp
interface iSK_INI : public IUnknown
{
  public:
    // BOM setting for the file (-1 = respect read file; 0 = never save with BOM; 1 = always save with BOM)
    // If no file is being read, -1 will always save with BOM. (ensures compatibility with Unreal Engine config tweaks)
    int enforceBOM = -1;
}
```
- Bethesda plugins adjusting the config should then just call `iSK_INI.enforceBOM=1;` after having created the iSK_INI object.

Sound accurate?

**Comment by Kaldaien** [comment]
Please don't change the order of bits in the enum :) The INI parser is used by third-party plug-ins. If you add a new type, it needs to be after the existing ones.

That aside, this looks like it works.

**Comment by Kaldaien** [comment]
> * BOM behavior should be changeable through a parameter in `iSK_INI`

Why? The type of encoding used for an INI file on first creation isn't currently changeable either. I though the problem we were trying to solve here was preserving BOM behavior of existing INI files?

**Comment by Aemony** [comment]
> Why? The type of encoding used for an INI file on first creation isn't currently changeable either. I thought the problem we were trying to solve here was preserving BOM behavior of existing INI files?

Starfield's adjustments uses a `StarfieldCustom.ini` file that the user might not currnetly already have. That file needs to be created without BOM for the game to recognize it if it is created through Special K :)

**Comment by Kaldaien** [comment]
Should all be fixed in 23.9.9.

I added a `set_encoding` method to iSK_INI. You must call that after creating an INI file if you want the newly created INI to have a specific encoding. Otherwise, it defaults to UTF8 with Byte Order Marker.

**Comment by Kaldaien** [comment]
No, nevermind. This is not a fix, this breaks all exisiting INI files.

**Comment by Kaldaien** [comment]
Closing the pull request because I've added the appropriate encoding options and updated the Bethesda plug-in to write INI files without BOM.

**Pull request closed without merging**
