### PR TITLE
Fix swapchain management scaling bug + compile bug on newer VS + graph transparency bug + build.bat / automated build process

### PR DESCRIPTION
**Pull request by Aemony**

### CODE REVIEW

**Comment by Aemony** [comment]
Added `build.bat` which is a batch file that should automatically load the VS Developer Command Prompt when run, as well as build both architectures through the regular batch files.

**Comment by Aemony** [comment]
Merged the changes of #25 into this one. I have still yet to find any actual downside to those changes.

**Comment by EndlesslyFlowering** [comment]
merge this please :)

**Comment by Aemony** [comment]
I am not familiar with GitHub enough to do a separate pull request, so I just merged the fix for stray Profiles/AppCache folders in the root of drives for local installs here as well. It needs some more testing though.

**Comment by Aemony** [comment]
> I am not familiar with GitHub enough to do a separate pull request, so I just merged the fix for stray Profiles/AppCache folders in the root of drives for local installs here as well. It needs some more testing though.

Special K still creates logs properly in all various scenarios I've tested:
- `w/ a global SK install` + `Global injection` = Works as expected 
- `w/ a global SK install` + `Local injection` + `Centralized profile` = Logs are stored in the global SK install.
- `w/ a global SK install` + `Local injection` + `Local profile` = Logs are stored in the game folder.
- `w/o a global SK install` + `Local injection` + `Centralized profile` = Logs are stored in the `Documents\My Mods\SpecialK` folder.
- `w/o a global SK install` + `Local injection` + `Local profile` = Logs are stored in the game folder.

**Comment by EndlesslyFlowering** [comment]
> I am not familiar with GitHub enough to do a separate pull request, so I just merged the fix for stray Profiles/AppCache folders in the root of drives for local installs here as well. It needs some more testing though.

I think the idea is that you create a separate branch for every PR.

**Comment by Aemony** [comment]
> > I am not familiar with GitHub enough to do a separate pull request, so I just merged the fix for stray Profiles/AppCache folders in the root of drives for local installs here as well. It needs some more testing though.
> 
> I think the idea is that you create a separate branch for every PR.

I am not familiar with GitHub or Git enough to create and maintain separate branches online and locally or whatever's needed to actually be able to do that...

And all changes I perform locally and push to my repo ends up automatically added to this PR as a result :|

**Comment by EndlesslyFlowering** [comment]
> > > I am not familiar with GitHub enough to do a separate pull request, so I just merged the fix for stray Profiles/AppCache folders in the root of drives for local installs here as well. It needs some more testing though.
> > 
> > 
> > I think the idea is that you create a separate branch for every PR.
> 
> I am not familiar with GitHub or Git enough to create and maintain separate branches online and locally or whatever's needed to actually be able to do that...
> 
> And all changes I perform locally and push to my repo ends up automatically added to this PR as a result :|

seems like you figured it out :) 👍

**Comment by Aemony** [comment]
All of these changes should now be merged.

**Pull request closed without merging**
