### PR TITLE
Add support for HDRMetadataType parameter

### PR DESCRIPTION
**Pull request by Aemony**
This adds the `HDRMetadataType=<int>` parameter which can be used to override the HDR metadata set by a game. This is apparently needed in some games on some displays as the displays may otherwise opt to use of some form of DTM over HGiG.

The user BR4P CITY on Discord experiences this issue with their `LG UltraGear OLED 27GR95QE` display with the recent remastered version of Dead Space, for example. They reported that using either `-2` (return S_OK without executing the call at all) or `0` (`DXGI_HDR_METADATA_TYPE_NONE`) solves their issue.

--

Apparently `IDXGISwapChain4::SetHDRMetaData()` should not even be used any longer, especially not for games since the HDR10 format it supports is meant to be used with HEVC videos.

To quote the Microsoft documentation:

> It is no longer recommended for apps to explicitly set HDR metadata on their swap chain using SetHDRMetaData. Windows does not guarantee that swap chain metadata is sent to the monitor, and monitors do not handle HDR metadata consistently. Therefore it's recommended that apps always tone-map content into the range reported by the monitor.

And on the `DXGI_HDR_METADATA_HDR10` type:

> Describes the metadata for HDR10, **used when video is compressed using High Efficiency Video Coding (HEVC).** This is used to describe the capabilities of the display used to master the content and the luminance values of the content.
> [...]
> This structure represents the definition of HDR10 metadata used with HEVC, **not HDR10 metadata for ST.2086.** These are closely related but defined differently.

--

**Supported values:**

* `-2` disables the function entirely; just returns S_OK without forwarding the call. Mostly intended for experimental purposes.
* `-1` respects the original value set by the game.
* `0` uses the type `DXGI_HDR_METADATA_TYPE_NONE` to indicate there is no header metadata.
* `1` uses the type `DXGI_HDR_METADATA_TYPE_HDR10` to indicate there is a HDR10 (HEVC video) structure in the header.
* `2` uses the type `DXGI_HDR_METADATA_TYPE_HDR10PLUS` to indicate there is a HDR10+ structure in the header (currently not used nor documented).

**Notes**

Special K also have `IWrapDXGISwapChain::SetHDRMetaData` in the `dxgi_swapchain.cpp` file, though I left this alone since in my testing `IDXGISwapChain4_SetHDRMetaData` in `dxgi.cpp` seemed to execute/influence the eventual input to `IWrapDXGISwapChain::SetHDRMetaData`.

### CODE REVIEW

**Comment by Aemony** [comment]
BR4P CITY confirmed on Discord that this change (that doesn't override the call in `dxgi_swapchain.cpp`) is enough to still fix their issue.

**Comment by DitherMan420** [comment]
Hello, this also helps me! I would love for this to be merged.

**Comment by mspeedo** [comment]
I vote for this merge as well, if voting is possible :)

**Comment by A-Coudray** [comment]
As an owner of a LG UltraGear OLED 27GR95QE, I can confim this helped me fix the HDR on FF7 Remake which is stuck on a 2000 tone map whereas the monitor should be using 603 (no dunamic tonemapping).

Having this feature merged on the master branch would be great.

**Comment by Zeryth1** [comment]
+1 on the merge, helps with multiple games on the 27GR95QE

**Comment by mspeedo** [comment]
Would it be possible please to add some "HDR Metadata" section to the gui which will display metadata values set by game? It would be helpful for analysis, as there is no way how to analyse that, other than buying some expensive device like HD Fury... or some LG monitors have that info in service menu.

**Comment by Aemony** [comment]
Note to everyone in this thread:
Latest commit removes the `0`-`2` values for the parameter entirely, and only leaves `-2` as a supported value. If you have been using `0` for the `HDRMetadataType` parameter, you need to manually change it to `-2` to retain the disabled behaviour.

A new installer will be pushed with this commit shortly.

**Pull request merged**
